import assert from 'node:assert/strict';
import { configuredBookFixture, configuredBookRaw } from './configured-book-fixture';
import { buildW0RunManifestFromConfig } from '../src/lib/books/build-run-manifest';
import { normalizeW0Manifest } from '../src/lib/books/normalize-w0-manifest';
import { resolvePagePlan } from '../src/lib/books/resolve-page-plan';
import { buildW2APoseWorklist } from '../src/lib/books/review-page-plan';
import { BookConfigSchema } from '../src/lib/books/types';
const config = configuredBookFixture();
const w0 = buildW0RunManifestFromConfig(config, { orderId: 'CONTRACT-01', platform: 'd2c', formatId: 'standard', characterHash: 'test-character', input: { characterSpecs: { childName: 'Ada', animalGuide: 'owl' } } });
assert.ok('renderSnapshot' in w0.book.resolved, 'W0 must freeze configured rendering for the actual order');
const snapshot = normalizeW0Manifest(w0);
assert.deepEqual(buildW2APoseWorklist(snapshot.pagePlan, { includeZeroPose: true, coverLayers: snapshot.renderSnapshot?.bookConfig.rendering.recipe?.covers.standard.layers }).map(p => p.poseNumber), [0, 13, 17, 18], 'W0-to-worklist must include secondary, repeated and cover-only poses exactly once');
assert.deepEqual(snapshot.requiredPoseNumbers, [13, 17, 18]);
assert.equal(snapshot.renderSnapshot?.bookConfig.rendering.recipe?.copy.title.text, 'A configured title');
config.rendering.recipe!.copy.title.text = 'LATEST MUTATION';
assert.equal(snapshot.renderSnapshot?.bookConfig.rendering.recipe?.copy.title.text, 'A configured title', 'Snapshot must be a deep copy');
const bad = structuredClone(w0); bad.book.bookConfigRef.version = 99;
assert.throws(() => normalizeW0Manifest(bad), /snapshot|identity/i, 'Normalization must reject conflicting version');
const duplicate = configuredBookRaw(); duplicate.rendering.recipe.poses['duplicate-run'] = { poseNumber: 13, referenceKey: 'book-contract-fixture/other.png' };
assert.throws(() => resolvePagePlan(BookConfigSchema.parse(duplicate), 'standard'), /duplicate.*pose|pose.*duplicate/i);
const missing = configuredBookRaw(); missing.formats.standard.interior.pageSequence[1].layers[0].poseId = 'missing';
assert.throws(() => resolvePagePlan(BookConfigSchema.parse(missing), 'standard'), /pose/i);
const outOfRange = configuredBookRaw(); outOfRange.rendering.recipe.poses['custom-run'].poseNumber = 100;
assert.throws(() => BookConfigSchema.parse(outOfRange));
const unsafe = configuredBookRaw(); unsafe.rendering.recipe.poses['custom-run'].referenceKey = '../private.png';
assert.throws(() => BookConfigSchema.parse(unsafe));
console.log('Configured book contract tests passed');
